### ISSUE TITLE
config dir not accessible

### ISSUE THREAD

**Issue by simon-carr-av** [danhale-git/runrdp#49]
**What am I trying to do?**
Access the configure directory created by runrdp 

**What is the problem I am facing?**
The directory created by configure is not accessible by the user, user receives access denied.

**Detail:**

Create the dir:

```
ip-10-10-17-153:~ simon.carr$ runrdp configure
config directory does not exist
create at /Users/simon.carr/.runrdp? (y/n): y
created directory  /Users/simon.carr/.runrdp
```

Attempt to access the dir:

```
ip-10-10-17-153:~ simon.carr$ cd /Users/simon.carr/.runrdp
-bash: cd: /Users/simon.carr/.runrdp: Permission denied
```

Checking permissions I see it is missing execute:

```
ip-10-10-17-153:~ simon.carr$ ls -ald /Users/simon.carr/.runrdp
drw-------  2 simon.carr  staff  64 17 Dec 12:19 /Users/simon.carr/.runrdp
```

Mitigate with:

```
ip-10-10-17-153:~ simon.carr$ chmod u+x /Users/simon.carr/.runrdp/

ip-10-10-17-153:.runrdp simon.carr$ ls -ald /Users/simon.carr/.runrdp
drwx------  2 simon.carr  staff  64 17 Dec 12:19 /Users/simon.carr/.runrdp
```

**Proposed solution:** 

User must have execute permissions on the directory created.

**Comment by danhale-git** [comment]
https://github.com/danhale-git/runrdp/commit/d03137ce33486f762ac14edb87e08c274c31a842
